language: elixir
elixir:
  - 1.2.0
  - 1.3.0
notifications:
  recipients:
    - spiros.gerokostas@gmail.com
otp_release:
  - 18.2
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile"
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
