language: elixir
elixir:
  - 1.3.0
  - 1.4.0
  - 1.5.0
notifications:
  recipients:
    - spiros.gerokostas@gmail.com
otp_release:
  - 18.2
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, coveralls.travis"
after_script:
  - "MIX_ENV=docs mix do deps.get, inch.report"
